--멤버스 테이블 생성
/*CREATE TABLE MEMBERS(
MEM_ID VARCHAR2(15) PRIMARY KEY,
MEM_PW VARCHAR2(20) NOT NULL,
MEM_NAME VARCHAR2(20) NOT NULL,
MEM_PHONE VARCHAR2(11)NOT NULL,
MEM_EMAIL VARCHAR2(100) NOT NULL,
MEM_ADDRESS VARCHAR2(200),
MEM_GRADE VARCHAR2(10) DEFAULT 'NORMAL' NOT NULL,
MEM_ROLE VARCHAR2(10) DEFAULT 'USER' NOT NULL,
MEM_DATE DATE DEFAULT SYSDATE NOT NULL
);
*/
--COMMIT;

 --상품 기본테이블 생성
/*CREATE TABLE PRODUCTS(
PRO_ID NUMBER PRIMARY KEY,
PRO_NAME VARCHAR2(50) NOT NULL,
PRO_PRICE NUMBER(10) NOT NULL,
PRO_CONTENT VARCHAR2(1000) NOT NULL,
PRO_IMG VARCHAR2(200),
PRO_CATEGORY VARCHAR2(20) NOT NULL,
PRO_DATE DATE DEFAULT SYSDATE NOT NULL
);
*/

--상품id 시퀀스 생성
/*
CREATE SEQUENCE SEQ_PRODUCTS
START WITH 000001
INCREMENT BY 1
NOCACHE
NOCYCLE;
*/

--상품옵션 테이블 생성
/*
CREATE TABLE PRO_OPTION(
OPTION_ID NUMBER PRIMARY KEY,
PRO_ID NUMBER NOT NULL,
PRO_SIZE VARCHAR2(10) DEFAULT 'FREE' NOT NULL,
PRO_COLOR VARCHAR2(30) NOT NULL,
PRO_STOCK NUMBER(4) DEFAULT 0 NOT NULL,

CONSTRAINT FK_PRO_OPTION
FOREIGN KEY (PRO_ID)
REFERENCES PRODUCTS(PRO_ID),

CONSTRAINT UQ_PRO_OPTION
 UNIQUE (PRO_ID, PRO_SIZE, PRO_COLOR),

CONSTRAINT CK_PRO_OPTION_STOCK
CHECK (PRO_STOCK>=0)

);
*/

--상품옵션ID 시퀀스 생성
/*
CREATE SEQUENCE SEQ_PRODUCTS_OPTION
START WITH 000001
INCREMENT BY 1
NOCACHE
NOCYCLE;
*/