--멤버스 테이블 생성
CREATE TABLE MEMBERS(
MEM_ID VARCHAR2(15) PRIMARY KEY,
MEM_PW VARCHAR2(20) NOT NULL,
MEM_NAME VARCHAR2(20) NOT NULL,
MEM_PHONE VARCHAR2(11)NOT NULL,
MEM_EMAIL VARCHAR2(100) NOT NULL,
MEM_ADDRESS VARCHAR2(200),
MEM_GRADE VARCHAR2(10) DEFAULT 'NORMAL' NOT NULL,
MEM_ROLE VARCHAR2(10) DEFAULT 'USER' NOT NULL,
MEM_DATE DATE DEFAULT SYSDATE NOT NULL
);

--COMMIT;

 --상품 기본테이블 생성
CREATE TABLE PRODUCTS(
PRO_ID NUMBER PRIMARY KEY,
PRO_NAME VARCHAR2(50) NOT NULL,
PRO_PRICE NUMBER(10) NOT NULL,
PRO_CONTENT VARCHAR2(1000) NOT NULL,
PRO_IMG VARCHAR2(200),
PRO_CATEGORY VARCHAR2(20) NOT NULL,
PRO_DATE DATE DEFAULT SYSDATE NOT NULL
);


--상품id 시퀀스 생성

CREATE SEQUENCE SEQ_PRODUCTS
START WITH 000001
INCREMENT BY 1
NOCACHE
NOCYCLE;


--상품옵션 테이블 생성

CREATE TABLE PRO_OPTION(
OPTION_ID NUMBER PRIMARY KEY,
PRO_ID NUMBER NOT NULL,
PRO_SIZE VARCHAR2(10) DEFAULT 'FREE' NOT NULL,
PRO_COLOR VARCHAR2(30) NOT NULL,
PRO_STOCK NUMBER(4) DEFAULT 0 NOT NULL,

CONSTRAINT FK_PRO_OPTION
FOREIGN KEY (PRO_ID)
REFERENCES PRODUCTS(PRO_ID),

CONSTRAINT UQ_PRO_OPTION
 UNIQUE (PRO_ID, PRO_SIZE, PRO_COLOR),

CONSTRAINT CK_PRO_OPTION_STOCK
CHECK (PRO_STOCK>=0)

);


--상품옵션ID 시퀀스 생성

CREATE SEQUENCE SEQ_PRODUCTS_OPTION
START WITH 000001
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- 상품 정보 입력
INSERT INTO PRODUCTS
VALUES(
SEQ_PRODUCTS.NEXTVAL,
'오버핏 후드',
39000,
'기본 후드티입니다',
'hoodie.jpg',
'TOP',
SYSDATE
);

INSERT INTO PRODUCTS
VALUES(
SEQ_PRODUCTS.NEXTVAL,
's스커트',
25000,
'우주 스커트',
'skirt.jpg',
'BOTTOM',
SYSDATE
);

SELECT * FROM PRODUCTS;
SELECT * FROM PRODUCTS WHERE PRO_CATEGORY = 'TOP';
SELECT COUNT(*) FROM PRODUCTS;


INSERT INTO PRO_OPTION VALUES (1, 1, 'M', 'BLACK', 10);
INSERT INTO PRO_OPTION VALUES (2, 1, 'L', 'BLACK', 5);
INSERT INTO PRO_OPTION VALUES (3, 1, 'M', 'WHITE', 3);
INSERT INTO PRO_OPTION VALUES (4, 1, 'L', 'WHITE', 7);

--카트 테이블
CREATE TABLE CART (
    CART_ID      NUMBER PRIMARY KEY,
    MEM_ID       VARCHAR2(50) NOT NULL,
    PRO_ID       NUMBER NOT NULL,
    OPTION_ID    NUMBER NOT NULL,
    CART_STOCK   NUMBER DEFAULT 1 NOT NULL,
    CREATE_DATE  DATE DEFAULT SYSDATE
);

--오더 기본 테이블
CREATE TABLE ORDERS (
    ORDER_ID        NUMBER PRIMARY KEY,
    MEM_ID          VARCHAR2(50) NOT NULL,
    RECEIVER_NAME   VARCHAR2(50) NOT NULL,
    RECEIVER_PHONE  VARCHAR2(30) NOT NULL,
    RECEIVER_ADDR   VARCHAR2(300) NOT NULL,
    DELIVERY_MEMO   VARCHAR2(500),
    PAYMENT         VARCHAR2(30) NOT NULL,
    TOTAL_PRICE     NUMBER NOT NULL,
    ORDER_DATE      DATE DEFAULT SYSDATE,
    ORDER_STATUS    VARCHAR2(30) DEFAULT '주문완료'
);

--오더 상세 테이블
CREATE TABLE ORDER_DETAIL (
    DETAIL_ID    NUMBER PRIMARY KEY,
    ORDER_ID     NUMBER NOT NULL,
    PRO_ID       NUMBER NOT NULL,
    PRO_OP_ID    NUMBER,
    PRO_NAME     VARCHAR2(100) NOT NULL,
    PRO_COLOR    VARCHAR2(50),
    PRO_SIZE     VARCHAR2(50),
    QUANTITY     NUMBER NOT NULL,
    PRO_PRICE    NUMBER NOT NULL,
    SUM_PRICE    NUMBER NOT NULL,
    
    CONSTRAINT FK_ORDER_DETAIL_ORDER
    FOREIGN KEY (ORDER_ID)
    REFERENCES ORDERS (ORDER_ID)
);

-- 오더 기본 시퀀스
CREATE SEQUENCE ORDERS_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

-- 오더 상세 시퀀스
CREATE SEQUENCE ORDER_DETAIL_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

