-- 멤버 정보 입력(관리자)
INSERT INTO MEMBERS (MEM_ID, MEM_PW, MEM_NAME, MEM_PHONE, MEM_EMAIL, MEM_ADDRESS, MEM_GRADE, MEM_ROLE)
VALUES ('ADMIN', '1234', '관리자', '01000000000', 'admin@test.com', '관리자 주소', 'ADMIN', 'ADMIN');

-- 멤버 정보 입력(사용자)
INSERT INTO MEMBERS (MEM_ID, MEM_PW, MEM_NAME, MEM_PHONE, MEM_EMAIL, MEM_ADDRESS, MEM_GRADE, MEM_ROLE)
VALUES ('TEST', '1234', '사용자', '01000000000', 'user@test.com', '사용자 주소', 'GREEN', 'USER');


-- 상품 정보 입력
INSERT INTO PRODUCTS VALUES(SEQ_PRODUCTS.NEXTVAL, '베이직 오버핏 티셔츠', 39000, '기본 오버핏 티셔츠입니다', 'basci_t.jpg', 'TOP', SYSDATE);

INSERT INTO PRO_OPTION VALUES (1, 1, 'M', 'BLACK', 10);
INSERT INTO PRO_OPTION VALUES (2, 1, 'L', 'BLACK', 5);
INSERT INTO PRO_OPTION VALUES (3, 1, 'M', 'WHITE', 3);
INSERT INTO PRO_OPTION VALUES (4, 1, 'L', 'WHITE', 7);

